POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Maria Fernanda",
    "email": "mariafernanda@labenu.com",
    "password": "batata1234",
    "role": "ADMIN"
}

### 

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "mariafernanda@labenu.com",
    "password": "batata1234"
}

### 

